version: '3'
services:
  consul:
    container_name: consul
    command: -server -advertise $DOCKER_IP -bootstrap
    ports:
     - "8300:8300"
     - "8301:8301"
     - "8400:8400"
     - "8500:8500"
     - "8600:53/udp"
    image: "rafaelszp/consul"

  time-service-app:
    container_name: time-service-app
    image: "rafaelszp/javaservice"
    ports:
      - "10080:10080/tcp"
      - "10443:10443/tcp"
    volumes:
      - "$PWD/javaservice/target/java-service-hollow-swarm.jar:/javaservice/java-service-hollow-swarm.jar:ro"
      - "$PWD/javaservice/target/java-service.war:/javaservice/java-service.war:ro"
      - "$PWD/javaservice/src/main/resources/project-stages.yml:/javaservice/project-stages.yml:ro"
    environment:
      - CONSUL_IP=$DOCKER_IP
    depends_on:
      - nginx-ct
      - consul

  nginx-ct:
    container_name: nginx_ct
    image: "rafaelszp/nginx-consul-template"
    ports:
      - "8080:80/tcp"
    volumes:
      - "$PWD/nginx/service.ctmpl:/templates/service.ctmpl"
    links:
      - consul
    depends_on:
      - consul